export enum DomainExceptionCode {
  // Blog content
  BLOG_NOT_FOUND = 'BLOG_NOT_FOUND',
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',

  // Security / sessions
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  SESSION_NOT_ACTIVE = 'SESSION_NOT_ACTIVE',
  USER_ALREADY_LOGGED_IN = 'USER_ALREADY_LOGGED_IN',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  LOGIN_ALREADY_EXISTS = 'LOGIN_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',

  // Auth
  CREDENTIALS_INCORRECT = 'CREDENTIALS_INCORRECT',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',
  CONFIRMATION_CODE_INVALID = 'CONFIRMATION_CODE_INVALID',
  CONFIRMATION_CODE_EXPIRED = 'CONFIRMATION_CODE_EXPIRED',
  RECOVERY_CODE_INVALID = 'RECOVERY_CODE_INVALID',
  RECOVERY_CODE_EXPIRED = 'RECOVERY_CODE_EXPIRED',

  // Access
  ACCESS_DENIED = 'ACCESS_DENIED',
}
