import { MigrationInterface, QueryRunner } from "typeorm";

export class AddQuestionsAndCorrectAnswers1775669948542 implements MigrationInterface {
    name = 'AddQuestionsAndCorrectAnswers1775669948542'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "typeorm"."correct_answers" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "answer" character varying NOT NULL, "questionId" integer NOT NULL, CONSTRAINT "PK_9774845e27d0898d99c97ed81ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "typeorm"."questions" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "body" character varying NOT NULL, "published" boolean NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "typeorm"."correct_answers" ADD CONSTRAINT "FK_b971cf511fea024a2134cc42abe" FOREIGN KEY ("questionId") REFERENCES "typeorm"."questions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "typeorm"."correct_answers" DROP CONSTRAINT "FK_b971cf511fea024a2134cc42abe"`);
        await queryRunner.query(`DROP TABLE "typeorm"."questions"`);
        await queryRunner.query(`DROP TABLE "typeorm"."correct_answers"`);
    }

}
