import { MigrationInterface, QueryRunner } from "typeorm";

export class AddQuizGameEntities1776070677307 implements MigrationInterface {
    name = 'AddQuizGameEntities1776070677307'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "typeorm"."games_status_enum" AS ENUM('pending', 'active', 'finished')`);
        await queryRunner.query(`CREATE TABLE "typeorm"."games" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "firstPlayerId" integer NOT NULL, "secondPlayerId" integer, "status" "typeorm"."games_status_enum" NOT NULL DEFAULT 'pending', "pairCreatedDate" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "startGameDate" TIMESTAMP WITH TIME ZONE, "finishGameDate" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_c9b16b62917b5595af982d66337" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "typeorm"."game_questions" ("gameId" integer NOT NULL, "questionId" integer NOT NULL, "questionNumber" smallint NOT NULL, CONSTRAINT "UQ_56b29fc50945cdf8f3c8250dc25" UNIQUE ("gameId", "questionNumber"), CONSTRAINT "CHK_e55b49a9ff5f49bf8b6e60d04a" CHECK ("questionNumber" >= 1 AND "questionNumber" <= 5), CONSTRAINT "PK_2248b533b855a8712e9a3fbc1a4" PRIMARY KEY ("gameId", "questionId"))`);
        await queryRunner.query(`CREATE TYPE "typeorm"."player_answers_status_enum" AS ENUM('correct', 'incorrect')`);
        await queryRunner.query(`CREATE TABLE "typeorm"."player_answers" ("gameId" integer NOT NULL, "questionId" integer NOT NULL, "userId" integer NOT NULL, "answer" character varying NOT NULL, "status" "typeorm"."player_answers_status_enum" NOT NULL, "addedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5ddf17c9742a141b81a7ce954d7" PRIMARY KEY ("gameId", "questionId", "userId"))`);
        await queryRunner.query(`ALTER TABLE "typeorm"."games" ADD CONSTRAINT "FK_8abad5fb430218ef8af88a034f2" FOREIGN KEY ("firstPlayerId") REFERENCES "typeorm"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "typeorm"."games" ADD CONSTRAINT "FK_c2c349d15f2ae8e0aae83f044d1" FOREIGN KEY ("secondPlayerId") REFERENCES "typeorm"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "typeorm"."game_questions" ADD CONSTRAINT "FK_a0545c377fe4b81dfb82497b19a" FOREIGN KEY ("gameId") REFERENCES "typeorm"."games"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "typeorm"."game_questions" ADD CONSTRAINT "FK_2f2de5b0489bd9ecea902b3c3e6" FOREIGN KEY ("questionId") REFERENCES "typeorm"."questions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "typeorm"."player_answers" ADD CONSTRAINT "FK_8b2c468b1ddd1001b761d992699" FOREIGN KEY ("userId") REFERENCES "typeorm"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "typeorm"."player_answers" ADD CONSTRAINT "FK_1111dc15b73c04d71d4d7ccef85" FOREIGN KEY ("gameId", "questionId") REFERENCES "typeorm"."game_questions"("gameId","questionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "typeorm"."player_answers" DROP CONSTRAINT "FK_1111dc15b73c04d71d4d7ccef85"`);
        await queryRunner.query(`ALTER TABLE "typeorm"."player_answers" DROP CONSTRAINT "FK_8b2c468b1ddd1001b761d992699"`);
        await queryRunner.query(`ALTER TABLE "typeorm"."game_questions" DROP CONSTRAINT "FK_2f2de5b0489bd9ecea902b3c3e6"`);
        await queryRunner.query(`ALTER TABLE "typeorm"."game_questions" DROP CONSTRAINT "FK_a0545c377fe4b81dfb82497b19a"`);
        await queryRunner.query(`ALTER TABLE "typeorm"."games" DROP CONSTRAINT "FK_c2c349d15f2ae8e0aae83f044d1"`);
        await queryRunner.query(`ALTER TABLE "typeorm"."games" DROP CONSTRAINT "FK_8abad5fb430218ef8af88a034f2"`);
        await queryRunner.query(`DROP TABLE "typeorm"."player_answers"`);
        await queryRunner.query(`DROP TYPE "typeorm"."player_answers_status_enum"`);
        await queryRunner.query(`DROP TABLE "typeorm"."game_questions"`);
        await queryRunner.query(`DROP TABLE "typeorm"."games"`);
        await queryRunner.query(`DROP TYPE "typeorm"."games_status_enum"`);
    }

}
